### ISSUE TITLE
Improvements on the styling

### ISSUE THREAD

**Issue by davidauza-engineer** [evaveskova/pomodoro-timer#3] opened 2020-03-10 22:15 UTC
Regarding #2, I found two issues in two different screen sizes using Chrome:

2560x1440:

![2560x1440](https://user-images.githubusercontent.com/47565678/76364145-7dc6a700-62f2-11ea-817e-a7eb460f66ce.png)

1281x720:

<img width="1281" alt="1281x720" src="https://user-images.githubusercontent.com/47565678/76364159-84edb500-62f2-11ea-9f24-f000e084cbfd.png">

Can you guys please take a look @onedebos, @hugopassos, @evaveskova 

Thank you very much

**Comment by onedebos** [comment] 2020-03-10 22:30
Hey @davidauza-engineer. I'm not sure I see what the problem is. What's breaking?

**Comment by evaveskova** [comment] 2020-03-11 15:31
Issue fixed in pull request #4

**Closed by evaveskova** 2020-03-11 15:31 UTC
Labels: bug
